# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CRM Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn', '~> 5.0'


  # Pods for CRM Manager

  target 'CRM ManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CRM ManagerUITests' do
    # Pods for testing
  end

end
